name: nop_station_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
 
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true
